apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: my-app
spec:
  selector:
    app.kubernates.io/name: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  