apiVersion: v1
kind: Service
metadata: 
  name: time-server
  namespace: my-app
spec: 
  selector: 
    app: time-server
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
      
     