apiVersion: v1
kind: Service
metadata: 
  name: auth-server
  namespace: my-app
spec: 
  selector: 
    app: auth-server
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      
     