name: helm-check-action

on: 
  push:
    branches:
      - main


jobs:
  halm-check:
    runs-on: ubuntu-latest
    steps: 
      - name: repository
        uses: actions/checkout@v3
      - name: install
        run: curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      - name: link
        run: | 
          helm lint time-server/
          helm lint auth-server/
